# Generated by Django 3.1.1 on 2020-09-28 09:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('theblog', '0002_auto_20200928_0925'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Postie',
            new_name='Post',
        ),
    ]
