# Generated by Django 3.1.1 on 2020-10-10 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0011_auto_20201010_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Click Link Aboe to Read Blog Post', max_length=100),
        ),
    ]
